#! /usr/bin/env python
# encoding: utf-8


APPNAME = 'kodo_relay_simulations'
VERSION = '1.0.0'


def recurse_helper(ctx, name):
    if not ctx.has_dependency_path(name):
        ctx.fatal('Load a tool to find %s as system dependency' % name)
    else:
        p = ctx.dependency_path(name)
        ctx.recurse(p)

def options(opt):

    import waflib.extras.wurf_dependency_bundle as bundle
    import waflib.extras.wurf_dependency_resolve as resolve
    import waflib.extras.wurf_configure_output

    bundle.add_dependency(opt,
        resolve.ResolveGitMajorVersion(
            name = 'waf-tools',
            git_repository = 'git://github.com/steinwurf/external-waf-tools.git',
            major_version = 2))

    bundle.add_dependency(opt,
        resolve.ResolveGitMajorVersion(
            name = 'gtest',
            git_repository = 'git://github.com/steinwurf/external-gtest.git',
            major_version = 2))

    bundle.add_dependency(opt,
        resolve.ResolveGitMajorVersion(
            name = 'boost',
            git_repository = 'git://github.com/steinwurf/external-boost-light.git',
            major_version = 1))

    bundle.add_dependency(opt,
        resolve.ResolveGitMajorVersion(
            name = 'sak',
            git_repository = 'git://github.com/steinwurf/sak.git',
            major_version = 8))

    bundle.add_dependency(opt,
        resolve.ResolveGitMajorVersion(
            name = 'fifi',
            git_repository = 'git://github.com/steinwurf/fifi.git',
            major_version = 6))

    bundle.add_dependency(opt,
        resolve.ResolveGitMajorVersion(
             name = 'kodo',
             git_repository = 'git://github.com/steinwurf/kodo.git',
             major_version = 7))

    opt.load('wurf_dependency_bundle')
    opt.load('wurf_tools')

def configure(conf):

    conf.load('wurf_tools')
    conf.load('wurf_dependency_bundle')

    conf.load_external_tool('mkspec', 'wurf_cxx_mkspec_tool')
    conf.load_external_tool('install_path', 'wurf_install_path')

    recurse_helper(conf, 'boost')
    recurse_helper(conf, 'gtest')
    recurse_helper(conf, 'sak')
    recurse_helper(conf, 'fifi')
    recurse_helper(conf, 'kodo')

def build(bld):

    bld.load('wurf_dependency_bundle')

    recurse_helper(bld, 'boost')
    recurse_helper(bld, 'gtest')
    recurse_helper(bld, 'sak')
    recurse_helper(bld, 'kodo')
    recurse_helper(bld, 'fifi')

    bld.recurse('relay_simulations')

